https://jsonplaceholder.typicode.com/posts/1
###

POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
    "title": "My Title",
    "body": "My text",
    "userId": 1
} 
###
http://127.0.0.1:8000/api/v1/categories/

###
