# Generated by Django 2.2.16 on 2022-01-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reviews", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="genres", name="name", field=models.CharField(max_length=256)
        )
    ]
