# Generated by Django 2.2.16 on 2022-01-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_auto_20220115_2315"),
        ("reviews", "0002_auto_20220116_0407"),
    ]

    operations = []
