# Generated by Django 2.2.16 on 2022-01-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reviews", "0003_merge_20220116_1244")]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="genres",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
    ]
